apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testing
  description: Python app that displays time. Named testing
  annotations:
    github.com/project-slug: silverkeytech/testing
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
