site_name: 'testing'
site_description: 'Main documentation for the testing'
repo_url: https://github.com/silverkeytech/testing
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
