replicaCount: 1
image:
  repository: registry.arc-center.run/silverkeytech/testing
  pullPolicy: IfNotPresent
  tag: testing-dev-latest
imagePullSecrets: 
   - name: gitea-registry-secret
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: testing-dev.arc-center.run
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 50M
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
